# Generated by Django 6.0.5 on 2026-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attributedefinition",
            name="unique_attr_def_per_content_type",
        ),
        migrations.RemoveConstraint(
            model_name="attributevalue",
            name="unique_attr_value_per_entity",
        ),
        migrations.RenameIndex(
            model_name="attributevalue",
            new_name="core_attrib_content_ca8481_idx",
            old_name="core_attributevalue_ct_obj_idx",
        ),
        migrations.AddField(
            model_name="attributedefinition",
            name="unit_family",
            field=models.CharField(
                blank=True,
                choices=[("length", "Length"), ("weight", "Weight"), ("volume", "Volume")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="value_number",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="value_unit",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="attributedefinition",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("long_text", "Long Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("single_select", "Single Select"),
                    ("dimension", "Dimension"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attributedefinition",
            unique_together={("content_type", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together={("attribute_definition", "content_type", "object_id")},
        ),
    ]
