# Generated by Django 6.0.5 on 2026-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attributevalue_value_number_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
