# Generated by Django 6.0.5 on 2026-07-20 15:16

import core.nanoid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_attributedefinition_emoji"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityView",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_key", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("pinned", models.BooleanField(default=False)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "table_key", "name"), name="unique_view_name_per_table"
                    )
                ],
            },
        ),
    ]
