# Generated by Django 6.0.5 on 2026-07-10 16:17

import core.nanoid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acquisition",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("purchase", "Purchase"),
                            ("gift", "Gift"),
                            ("transfer", "Transfer"),
                            ("found", "Found"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("obtained_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-obtained_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("stockable", "Stockable"), ("consumable", "Consumable")],
                        default="stockable",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "length",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "width",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "height",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=100)),
                (
                    "weight",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("purchase_time", models.DateTimeField(blank=True, null=True)),
                ("storage_location", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acquisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.acquisition",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("mutual_exclusive", "Mutually exclusive"),
                            ("required", "Required"),
                            ("weight_limit", "Weight limit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_category", models.CharField(blank=True, max_length=100)),
                (
                    "limit_value",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="constraints", to="inventory.item"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="inventory.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.nanoid.generate_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "required_quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=20),
                ),
                ("prepared", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contained_items",
                        to="inventory.scenarioitem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_items",
                        to="inventory.item",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("scenario", "item")},
            },
        ),
    ]
