# Generated by Django 6.0.5 on 2026-07-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_drop_param_columns_scenario_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioitem',
            name='organized',
            field=models.BooleanField(default=False),
        ),
    ]
