# Generated by Django 6.0.5 on 2026-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_scenarioitem_organized"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="alias_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
