# Generated by Django 6.0.5 on 2026-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_seed_diameter_temperature"),
    ]

    def backfill(apps, schema_editor):
        Item = apps.get_model("inventory", "Item")
        Item.objects.filter(deprecate_time__isnull=False).update(deprecated=True)

    operations = [
        migrations.AddField(
            model_name="item",
            name="deprecated",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
