# Generated by Django 6.0.5 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_seed_waist"),
    ]

    operations = [
        migrations.AddField(
            model_name="costfactor",
            name="user_managed",
            field=models.BooleanField(default=False),
        ),
    ]
