# Generated by Django 6.0.5 on 2026-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_balancesheet_exchangerate_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="balance",
            name="unique_balance_per_account_sheet",
        ),
        migrations.RemoveConstraint(
            model_name="exchangerate",
            name="unique_exchange_rate_per_date",
        ),
        migrations.AddField(
            model_name="account",
            name="close_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="open_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="balance",
            unique_together={("account", "balance_sheet")},
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("base_currency", "quote_currency", "date")},
        ),
    ]
