# Generated by Django 6.0.5 on 2026-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_account_datetime_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="is_base_currency",
            field=models.BooleanField(default=False),
        ),
    ]
