# Generated by Django 6.0.5 on 2026-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_currency_add_is_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
