# Generated by Django 6.0.5 on 2026-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_account_add_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
