# Generated by Django 6.0.5 on 2026-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_asset_portfolio_transaction_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='chain_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='transfer',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='asset_change_amount',
            field=models.DecimalField(decimal_places=18, max_digits=38),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='value_change',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True),
        ),
    ]
