# Generated by Django 6.0.5 on 2026-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_asset_category_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
